CREATE DATABASE IF NOT EXISTS ludoteca;
USE ludoteca;

#CATEGORIAS
ALTER TABLE PRODUCTOS  DROP FOREIGN KEY fk_producto_categoria_id;
DROP TABLE IF EXISTS `CATEGORIAS`;

CREATE TABLE `CATEGORIAS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
)

#PRODUCTOS

DROP TABLE `PRODUCTOS`;

CREATE TABLE `PRODUCTOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `PRECIO` int NOT NULL,
  `STOCK` int DEFAULT NULL,
  `DESCRIPCION` varchar(1000) NOT NULL,
  `CATEGORIA_ID` int,
  PRIMARY KEY (`ID`),
  KEY `CATEGORIA_ID` (`CATEGORIA_ID`),
  CONSTRAINT `fk_produto_categoria_id`
        FOREIGN KEY (`CATEGORIA_ID`)
        REFERENCES `CATEGORIAS` (`ID`)
        ON DELETE CASCADE
);