CREATE DATABASE IF NOT EXISTS ludoteca;
USE ludoteca;

#CATEGORIAS
DROP TABLE IF EXISTS `CATEGORIAS`;

CREATE TABLE `CATEGORIAS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
)

#PRODUCTOS

DROP TABLE `PRODUCTOS`;

CREATE TABLE `PRODUCTOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `PRECIO` int NOT NULL,
  `STOCK` int DEFAULT NULL,
  `DESCRIPCION` varchar(1000) NOT NULL,
  `ID_CATEGORIA` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CATEGORIA_ID` (`ID_CATEGORIA`),
  CONSTRAINT `fk_produto_categoria_id`
        FOREIGN KEY (`ID_CATEGORIA`)
        REFERENCES `CATEGORIAS` (`ID`)
        ON DELETE CASCADE
);