CREATE DATABASE IF NOT EXISTS ludoteca_admin;
USE ludoteca_admin;


CREATE TABLE `ADMIN` (
  `ID_ADMIN` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_ADMIN` varchar(255) NOT NULL,
  `CONTRASENIA` varchar(255) NOT NULL,
  `EMAIL_ADMIN` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_ADMIN`)
)

INSERT INTO `ADMIN` (NOMBRE_ADMIN,EMAIL_ADMIN,CONTRASENIA) VALUES ('Tomas','tomas@gmail.com','1234');
INSERT INTO `ADMIN` (NOMBRE_ADMIN,EMAIL_ADMIN,CONTRASENIA) VALUES ('Santiago','Santiago@gmail.com','1234');