CREATE DATABASE IF NOT EXISTS Ludoteca;
USE Ludoteca;

-- ADMIN
DROP TABLE IF EXISTS `ADMIN`;
CREATE TABLE `ADMIN` (
  `ID_ADMIN` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_ADMIN` varchar(255) NOT NULL,
  `CONTRASENIA` varchar(255) NOT NULL,
  `EMAIL_ADMIN` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_ADMIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- USUARIO
DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE `USUARIO` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `CONTRASENIA` varchar(255) NOT NULL,
  `NOMBRE` varchar(255) NOT NULL,
  `DIRECCION` varchar(255) NOT NULL,
  `PISO` int NOT NULL,
  `TIMBRE` varchar(10) NOT NULL,
  `APELLIDO` varchar(255) NOT NULL,
  `DNI` int NOT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- CATEGORIA
DROP TABLE IF EXISTS `CATEGORIA`;
CREATE TABLE `CATEGORIA` (
  `ID_CATEGORIA` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_DE_CATEGORIA` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- PRODUCTOS
DROP TABLE IF EXISTS `PRODUCTOS`;
CREATE TABLE `PRODUCTOS` (
  `ID_PRODUCTOS` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_DEL_PRODUCTO` varchar(255) NOT NULL,
  `PRECIO` int NOT NULL,
  `STOCK` int DEFAULT NULL,
  `DESCRIPCION` varchar(1000) NOT NULL,
  `ID_CATEGORIA` int NOT NULL,
  PRIMARY KEY (`ID_PRODUCTOS`),
  KEY `ID_CATEGORIA` (`ID_CATEGORIA`),
  CONSTRAINT `PRODUCTOS_ibfk_1` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `CATEGORIA` (`ID_CATEGORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- CARRITO
DROP TABLE IF EXISTS `CARRITO`;
CREATE TABLE `CARRITO` (
  `ID_CARRITO` int NOT NULL AUTO_INCREMENT,
  `ID_PRODUCTOS` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `FECHA` date NOT NULL,
  `CANTIDAD` int NOT NULL,
  PRIMARY KEY (`ID_CARRITO`),
  KEY `ID_PRODUCTOS` (`ID_PRODUCTOS`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `CARRITO_ibfk_1` FOREIGN KEY (`ID_PRODUCTOS`) REFERENCES `PRODUCTOS` (`ID_PRODUCTOS`),
  CONSTRAINT `CARRITO_ibfk_2` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- COMPRAS
DROP TABLE IF EXISTS `COMPRAS`;
CREATE TABLE `COMPRAS` (
  `ID_COMPRAS` int NOT NULL AUTO_INCREMENT,
  `FECHA_DE_COMPRA` date NOT NULL,
  `ID_PRODUCTO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `CANTIDAD_PRODUCTO` int NOT NULL,
  `TOTAL_PRECIO` int NOT NULL,
  `METODO_DE_PAGO` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_COMPRAS`),
  KEY `ID_PRODUCTO` (`ID_PRODUCTO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `COMPRAS_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTOS` (`ID_PRODUCTOS`),
  CONSTRAINT `COMPRAS_ibfk_2` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Mostrar las tablas
SHOW TABLES;

-- INSERTS
INSERT INTO `ADMIN` (NOMBRE_ADMIN,EMAIL_ADMIN,CONTRASENIA) VALUES ('Tomas','tomas@gmail.com','1234');
INSERT INTO `ADMIN` (NOMBRE_ADMIN,EMAIL_ADMIN,CONTRASENIA) VALUES ('Santiago','Santiago@gmail.com','1234');
